// <auto-generated />
using System;
using AddressBook.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddressBook.Api.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressBook.Api.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookEntryId")
                        .HasColumnType("int");

                    b.Property<string>("CityTown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateProvince")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookEntryId");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            BookEntryId = 26,
                            CityTown = "Donnellyhaven",
                            Country = "Timor-Leste",
                            Line1 = "91620 Agustin Neck",
                            Line2 = "Apt. 847",
                            Line3 = "Apt. 840",
                            PostalCode = "75107",
                            StateProvince = "Massachusetts"
                        },
                        new
                        {
                            Id = 52,
                            BookEntryId = 26,
                            CityTown = "Travisfort",
                            Country = "Bangladesh",
                            Line1 = "49921 Leopold Estate",
                            Line2 = "Suite 715",
                            Line3 = "Apt. 237",
                            PostalCode = "26584-0541",
                            StateProvince = "Minnesota"
                        },
                        new
                        {
                            Id = 53,
                            BookEntryId = 27,
                            CityTown = "West Rowland",
                            Country = "Belgium",
                            Line1 = "94899 Norma Square",
                            Line2 = "Apt. 796",
                            Line3 = "Apt. 724",
                            PostalCode = "84181-4394",
                            StateProvince = "Oregon"
                        },
                        new
                        {
                            Id = 54,
                            BookEntryId = 27,
                            CityTown = "West Geovanny",
                            Country = "Saint Lucia",
                            Line1 = "10844 Willms Meadow",
                            Line3 = "Apt. 208",
                            PostalCode = "52085-1746",
                            StateProvince = "Texas"
                        },
                        new
                        {
                            Id = 55,
                            BookEntryId = 28,
                            CityTown = "Nilsmouth",
                            Country = "Afghanistan",
                            Line1 = "15333 Taylor Ferry",
                            Line2 = "Apt. 506",
                            Line3 = "Apt. 316",
                            PostalCode = "80092-7223",
                            StateProvince = "Wyoming"
                        },
                        new
                        {
                            Id = 56,
                            BookEntryId = 28,
                            CityTown = "Dachbury",
                            Country = "Belize",
                            Line1 = "790 Luigi Port",
                            Line3 = "Suite 386",
                            PostalCode = "93144",
                            StateProvince = "Michigan"
                        },
                        new
                        {
                            Id = 57,
                            BookEntryId = 29,
                            CityTown = "New Geoton",
                            Country = "Ecuador",
                            Line1 = "722 Lizeth Prairie",
                            Line2 = "Apt. 906",
                            Line3 = "Apt. 105",
                            PostalCode = "26651",
                            StateProvince = "Massachusetts"
                        },
                        new
                        {
                            Id = 58,
                            BookEntryId = 29,
                            CityTown = "Larkinborough",
                            Country = "Latvia",
                            Line1 = "07671 Wisoky Summit",
                            Line2 = "Apt. 618",
                            Line3 = "Suite 612",
                            PostalCode = "54740-1602",
                            StateProvince = "South Dakota"
                        },
                        new
                        {
                            Id = 59,
                            BookEntryId = 30,
                            CityTown = "Wymanchester",
                            Country = "Iraq",
                            Line1 = "29994 Keebler Common",
                            Line2 = "Suite 957",
                            Line3 = "Suite 432",
                            PostalCode = "59260",
                            StateProvince = "Illinois"
                        },
                        new
                        {
                            Id = 60,
                            BookEntryId = 30,
                            CityTown = "New Garettfort",
                            Country = "Belarus",
                            Line1 = "971 Torrance Loaf",
                            Line3 = "Suite 699",
                            PostalCode = "73405-3628",
                            StateProvince = "South Dakota"
                        },
                        new
                        {
                            Id = 61,
                            BookEntryId = 31,
                            CityTown = "Genevievetown",
                            Country = "Netherlands",
                            Line1 = "071 Rowena Forges",
                            Line3 = "Apt. 769",
                            PostalCode = "81046",
                            StateProvince = "South Carolina"
                        },
                        new
                        {
                            Id = 62,
                            BookEntryId = 31,
                            CityTown = "Heidenreichland",
                            Country = "France",
                            Line1 = "86714 Jonas Flats",
                            Line3 = "Apt. 291",
                            PostalCode = "03737-1515",
                            StateProvince = "North Carolina"
                        },
                        new
                        {
                            Id = 63,
                            BookEntryId = 32,
                            CityTown = "Lake Vidal",
                            Country = "Panama",
                            Line1 = "098 Clemmie Lane",
                            Line2 = "Apt. 448",
                            Line3 = "Suite 791",
                            PostalCode = "01594-4257",
                            StateProvince = "Colorado"
                        },
                        new
                        {
                            Id = 64,
                            BookEntryId = 32,
                            CityTown = "Harriston",
                            Country = "Sao Tome and Principe",
                            Line1 = "73950 Brandon Run",
                            Line2 = "Apt. 027",
                            Line3 = "Suite 702",
                            PostalCode = "09144",
                            StateProvince = "Illinois"
                        },
                        new
                        {
                            Id = 65,
                            BookEntryId = 33,
                            CityTown = "O'Reillyburgh",
                            Country = "Barbados",
                            Line1 = "584 Martina Ramp",
                            Line3 = "Suite 998",
                            PostalCode = "95080-7824",
                            StateProvince = "Iowa"
                        },
                        new
                        {
                            Id = 66,
                            BookEntryId = 33,
                            CityTown = "Langworthfurt",
                            Country = "New Zealand",
                            Line1 = "29967 Antonia Bypass",
                            Line2 = "Suite 980",
                            Line3 = "Apt. 011",
                            PostalCode = "16676",
                            StateProvince = "South Carolina"
                        },
                        new
                        {
                            Id = 67,
                            BookEntryId = 34,
                            CityTown = "Norbertton",
                            Country = "Nicaragua",
                            Line1 = "6976 Monroe Isle",
                            Line2 = "Suite 765",
                            Line3 = "Suite 792",
                            PostalCode = "75589",
                            StateProvince = "South Carolina"
                        },
                        new
                        {
                            Id = 68,
                            BookEntryId = 34,
                            CityTown = "Jaquanmouth",
                            Country = "Montenegro",
                            Line1 = "54324 Christiansen Freeway",
                            Line3 = "Suite 182",
                            PostalCode = "65098-0080",
                            StateProvince = "West Virginia"
                        },
                        new
                        {
                            Id = 69,
                            BookEntryId = 35,
                            CityTown = "Vladimirfort",
                            Country = "Israel",
                            Line1 = "269 Maribel Lane",
                            Line3 = "Apt. 947",
                            PostalCode = "26944-4305",
                            StateProvince = "Maryland"
                        },
                        new
                        {
                            Id = 70,
                            BookEntryId = 35,
                            CityTown = "North Orlo",
                            Country = "Cayman Islands",
                            Line1 = "8105 Ocie Divide",
                            Line2 = "Apt. 340",
                            Line3 = "Suite 043",
                            PostalCode = "10482-4159",
                            StateProvince = "Delaware"
                        },
                        new
                        {
                            Id = 71,
                            BookEntryId = 36,
                            CityTown = "Clovisborough",
                            Country = "South Georgia and the South Sandwich Islands",
                            Line1 = "839 Nader Oval",
                            Line2 = "Apt. 168",
                            Line3 = "Apt. 630",
                            PostalCode = "46133",
                            StateProvince = "Maryland"
                        },
                        new
                        {
                            Id = 72,
                            BookEntryId = 36,
                            CityTown = "Kozeyville",
                            Country = "Dominican Republic",
                            Line1 = "69278 Leuschke Track",
                            Line3 = "Apt. 340",
                            PostalCode = "84439-4490",
                            StateProvince = "Washington"
                        },
                        new
                        {
                            Id = 73,
                            BookEntryId = 37,
                            CityTown = "North Kentonside",
                            Country = "El Salvador",
                            Line1 = "612 Myriam Roads",
                            Line2 = "Apt. 022",
                            Line3 = "Apt. 336",
                            PostalCode = "02598-3190",
                            StateProvince = "Vermont"
                        },
                        new
                        {
                            Id = 74,
                            BookEntryId = 37,
                            CityTown = "Ardellashire",
                            Country = "Gibraltar",
                            Line1 = "56299 Mason Hills",
                            Line2 = "Apt. 651",
                            Line3 = "Suite 717",
                            PostalCode = "41247-8216",
                            StateProvince = "Minnesota"
                        },
                        new
                        {
                            Id = 75,
                            BookEntryId = 38,
                            CityTown = "Franeckistad",
                            Country = "Romania",
                            Line1 = "33993 Triston Ridges",
                            Line3 = "Suite 929",
                            PostalCode = "34820-2497",
                            StateProvince = "Alabama"
                        },
                        new
                        {
                            Id = 76,
                            BookEntryId = 38,
                            CityTown = "West Tylerfurt",
                            Country = "Belize",
                            Line1 = "319 Amy Rue",
                            Line3 = "Apt. 189",
                            PostalCode = "39478",
                            StateProvince = "Wyoming"
                        },
                        new
                        {
                            Id = 77,
                            BookEntryId = 39,
                            CityTown = "East Deltaborough",
                            Country = "South Georgia and the South Sandwich Islands",
                            Line1 = "971 Glover River",
                            Line2 = "Apt. 272",
                            Line3 = "Suite 961",
                            PostalCode = "77717",
                            StateProvince = "Utah"
                        },
                        new
                        {
                            Id = 78,
                            BookEntryId = 39,
                            CityTown = "Melynaside",
                            Country = "Ireland",
                            Line1 = "1095 Aimee Flat",
                            Line2 = "Apt. 189",
                            Line3 = "Suite 611",
                            PostalCode = "86824-9154",
                            StateProvince = "New Mexico"
                        },
                        new
                        {
                            Id = 79,
                            BookEntryId = 40,
                            CityTown = "North Westleymouth",
                            Country = "Virgin Islands, U.S.",
                            Line1 = "8629 Jeffrey Parkways",
                            PostalCode = "52846",
                            StateProvince = "Maine"
                        },
                        new
                        {
                            Id = 80,
                            BookEntryId = 40,
                            CityTown = "New Joanne",
                            Country = "Mauritania",
                            Line1 = "5662 Jordi Flat",
                            Line2 = "Suite 496",
                            Line3 = "Apt. 284",
                            PostalCode = "36730",
                            StateProvince = "Iowa"
                        },
                        new
                        {
                            Id = 81,
                            BookEntryId = 41,
                            CityTown = "Gutkowskiview",
                            Country = "Cayman Islands",
                            Line1 = "095 Verla Haven",
                            Line2 = "Suite 509",
                            Line3 = "Apt. 601",
                            PostalCode = "43101",
                            StateProvince = "Maine"
                        },
                        new
                        {
                            Id = 82,
                            BookEntryId = 41,
                            CityTown = "New Elliotport",
                            Country = "Guadeloupe",
                            Line1 = "276 Laron Ridge",
                            Line3 = "Suite 827",
                            PostalCode = "70369-6197",
                            StateProvince = "Georgia"
                        },
                        new
                        {
                            Id = 83,
                            BookEntryId = 42,
                            CityTown = "Lebsackhaven",
                            Country = "Mauritania",
                            Line1 = "994 Heidenreich Corner",
                            Line3 = "Apt. 216",
                            PostalCode = "78680-6123",
                            StateProvince = "Colorado"
                        },
                        new
                        {
                            Id = 84,
                            BookEntryId = 42,
                            CityTown = "Anselberg",
                            Country = "Bhutan",
                            Line1 = "627 Juliana Island",
                            Line2 = "Suite 100",
                            Line3 = "Suite 947",
                            PostalCode = "29440-8728",
                            StateProvince = "Missouri"
                        },
                        new
                        {
                            Id = 85,
                            BookEntryId = 43,
                            CityTown = "West Jared",
                            Country = "Gambia",
                            Line1 = "28670 Chauncey Ports",
                            Line2 = "Suite 571",
                            Line3 = "Suite 691",
                            PostalCode = "68118-0819",
                            StateProvince = "Georgia"
                        },
                        new
                        {
                            Id = 86,
                            BookEntryId = 43,
                            CityTown = "Boylechester",
                            Country = "Turkmenistan",
                            Line1 = "9444 Arjun Rue",
                            Line2 = "Suite 613",
                            Line3 = "Apt. 281",
                            PostalCode = "03649",
                            StateProvince = "Indiana"
                        },
                        new
                        {
                            Id = 87,
                            BookEntryId = 44,
                            CityTown = "Domingofurt",
                            Country = "Guatemala",
                            Line1 = "4483 Shields Ville",
                            Line3 = "Apt. 453",
                            PostalCode = "20190",
                            StateProvince = "Rhode Island"
                        },
                        new
                        {
                            Id = 88,
                            BookEntryId = 44,
                            CityTown = "New Rethaborough",
                            Country = "Uruguay",
                            Line1 = "245 Marquardt Radial",
                            Line2 = "Suite 679",
                            Line3 = "Suite 927",
                            PostalCode = "64656",
                            StateProvince = "Michigan"
                        },
                        new
                        {
                            Id = 89,
                            BookEntryId = 45,
                            CityTown = "Gleasonburgh",
                            Country = "Costa Rica",
                            Line1 = "9347 Ankunding Grove",
                            Line3 = "Suite 389",
                            PostalCode = "59529",
                            StateProvince = "Tennessee"
                        },
                        new
                        {
                            Id = 90,
                            BookEntryId = 45,
                            CityTown = "West Kraig",
                            Country = "Lao People's Democratic Republic",
                            Line1 = "317 Trantow Landing",
                            Line3 = "Apt. 678",
                            PostalCode = "66963",
                            StateProvince = "North Carolina"
                        },
                        new
                        {
                            Id = 91,
                            BookEntryId = 46,
                            CityTown = "Romagueraton",
                            Country = "French Polynesia",
                            Line1 = "3115 Jennings Mills",
                            Line3 = "Apt. 091",
                            PostalCode = "56952-2467",
                            StateProvince = "Minnesota"
                        },
                        new
                        {
                            Id = 92,
                            BookEntryId = 46,
                            CityTown = "Monserrateburgh",
                            Country = "Holy See (Vatican City State)",
                            Line1 = "8562 Simonis Rapid",
                            Line3 = "Apt. 578",
                            PostalCode = "88358",
                            StateProvince = "Wyoming"
                        },
                        new
                        {
                            Id = 93,
                            BookEntryId = 47,
                            CityTown = "Lake Jamie",
                            Country = "Qatar",
                            Line1 = "621 Petra Isle",
                            Line2 = "Apt. 831",
                            Line3 = "Apt. 141",
                            PostalCode = "25857-9849",
                            StateProvince = "New Mexico"
                        },
                        new
                        {
                            Id = 94,
                            BookEntryId = 47,
                            CityTown = "East Terrencehaven",
                            Country = "Netherlands Antilles",
                            Line1 = "7536 Reinger Rapids",
                            Line3 = "Suite 047",
                            PostalCode = "25041",
                            StateProvince = "Idaho"
                        },
                        new
                        {
                            Id = 95,
                            BookEntryId = 48,
                            CityTown = "North Stacy",
                            Country = "Senegal",
                            Line1 = "1740 Trevion Road",
                            Line2 = "Suite 482",
                            Line3 = "Apt. 939",
                            PostalCode = "97654-2484",
                            StateProvince = "North Dakota"
                        },
                        new
                        {
                            Id = 96,
                            BookEntryId = 48,
                            CityTown = "Mariellemouth",
                            Country = "Honduras",
                            Line1 = "872 Katarina View",
                            Line2 = "Suite 470",
                            Line3 = "Suite 022",
                            PostalCode = "89951-9835",
                            StateProvince = "Nevada"
                        },
                        new
                        {
                            Id = 97,
                            BookEntryId = 49,
                            CityTown = "North Olaf",
                            Country = "Marshall Islands",
                            Line1 = "997 Peyton Springs",
                            Line2 = "Suite 327",
                            Line3 = "Apt. 052",
                            PostalCode = "93502",
                            StateProvince = "Idaho"
                        },
                        new
                        {
                            Id = 98,
                            BookEntryId = 49,
                            CityTown = "Kuvalisfurt",
                            Country = "Nigeria",
                            Line1 = "266 Catalina Rest",
                            Line2 = "Apt. 417",
                            Line3 = "Suite 140",
                            PostalCode = "04618-4429",
                            StateProvince = "Rhode Island"
                        },
                        new
                        {
                            Id = 99,
                            BookEntryId = 50,
                            CityTown = "Lake Sydneeport",
                            Country = "Nigeria",
                            Line1 = "1838 Fadel Plaza",
                            Line2 = "Suite 513",
                            Line3 = "Apt. 942",
                            PostalCode = "60082-9211",
                            StateProvince = "Tennessee"
                        },
                        new
                        {
                            Id = 100,
                            BookEntryId = 50,
                            CityTown = "Hartmannshire",
                            Country = "Serbia",
                            Line1 = "9180 Horacio Unions",
                            Line2 = "Apt. 817",
                            Line3 = "Suite 927",
                            PostalCode = "91745",
                            StateProvince = "Utah"
                        });
                });

            modelBuilder.Entity("AddressBook.Api.Data.Entities.BookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookEntries");

                    b.HasData(
                        new
                        {
                            Id = 26,
                            AddressName = "Markets Meadow",
                            CellPhone = "838-307-2303",
                            CompanyName = "O'Keefe, Dibbert and Hartmann",
                            DateOfBirth = new DateTime(1957, 8, 3, 16, 43, 25, 655, DateTimeKind.Local).AddTicks(129),
                            Email = "Prince_Ebert29@yahoo.com",
                            FirstName = "Prince",
                            Gender = "Female",
                            HomePhone = "591-947-8944",
                            LastName = "Ebert",
                            MiddleName = "Brody"
                        },
                        new
                        {
                            Id = 27,
                            AddressName = "Dynamic Personal Loan Account",
                            CompanyName = "Trantow, Kautzer and Hagenes",
                            DateOfBirth = new DateTime(1955, 2, 12, 8, 2, 7, 801, DateTimeKind.Local).AddTicks(7449),
                            Email = "Brenden.Kuhn72@gmail.com",
                            FirstName = "Brenden",
                            Gender = "Male",
                            LastName = "Kuhn",
                            MiddleName = "Otto"
                        },
                        new
                        {
                            Id = 28,
                            AddressName = "Borders withdrawal",
                            CompanyName = "Schroeder - Mayer",
                            DateOfBirth = new DateTime(1983, 2, 2, 9, 43, 23, 191, DateTimeKind.Local).AddTicks(7300),
                            Email = "Newton_Schneider@yahoo.com",
                            FirstName = "Newton",
                            Gender = "Female",
                            HomePhone = "701-554-6047",
                            LastName = "Schneider",
                            MiddleName = "Trent"
                        },
                        new
                        {
                            Id = 29,
                            AddressName = "extend parse",
                            CellPhone = "252-293-0720",
                            CompanyName = "Schamberger, Schamberger and Huel",
                            DateOfBirth = new DateTime(1983, 7, 20, 1, 39, 15, 648, DateTimeKind.Local).AddTicks(9974),
                            Email = "Dexter74@hotmail.com",
                            FirstName = "Dexter",
                            Gender = "Male",
                            LastName = "Thompson",
                            MiddleName = "Peyton"
                        },
                        new
                        {
                            Id = 30,
                            AddressName = "optical rich",
                            CompanyName = "Fay, Wilkinson and Carroll",
                            DateOfBirth = new DateTime(1991, 2, 4, 19, 33, 19, 912, DateTimeKind.Local).AddTicks(3397),
                            Email = "Pearlie_Maggio@yahoo.com",
                            FirstName = "Pearlie",
                            Gender = "Male",
                            HomePhone = "654-214-3383",
                            LastName = "Maggio",
                            MiddleName = "Jessica",
                            WorkPhone = "623-425-0471"
                        },
                        new
                        {
                            Id = 31,
                            AddressName = "Practical Granite Gloves aggregate",
                            CellPhone = "739-788-1723",
                            CompanyName = "Schuppe Inc",
                            DateOfBirth = new DateTime(1995, 9, 24, 13, 10, 1, 121, DateTimeKind.Local).AddTicks(6634),
                            Email = "Verdie.Denesik4@hotmail.com",
                            FirstName = "Verdie",
                            Gender = "Female",
                            HomePhone = "481-801-3228",
                            LastName = "Denesik",
                            MiddleName = "Kylee"
                        },
                        new
                        {
                            Id = 32,
                            AddressName = "Cambridgeshire wireless",
                            CellPhone = "691-946-0334",
                            CompanyName = "Kohler and Sons",
                            DateOfBirth = new DateTime(2002, 7, 16, 12, 40, 28, 3, DateTimeKind.Local).AddTicks(3434),
                            Email = "Alvah94@hotmail.com",
                            FirstName = "Alvah",
                            Gender = "Male",
                            LastName = "Gerlach",
                            MiddleName = "Nola"
                        },
                        new
                        {
                            Id = 33,
                            AddressName = "Gorgeous Fantastic Wooden Pants",
                            CellPhone = "385-660-2121",
                            CompanyName = "Rempel and Sons",
                            DateOfBirth = new DateTime(1992, 2, 11, 10, 26, 17, 186, DateTimeKind.Local).AddTicks(3175),
                            Email = "Sadie_Weber@hotmail.com",
                            FirstName = "Sadie",
                            Gender = "Male",
                            LastName = "Weber",
                            MiddleName = "Guido",
                            WorkPhone = "772-975-8087"
                        },
                        new
                        {
                            Id = 34,
                            AddressName = "redundant Steel",
                            CompanyName = "Runolfsson LLC",
                            DateOfBirth = new DateTime(1961, 7, 16, 13, 50, 38, 359, DateTimeKind.Local).AddTicks(8389),
                            Email = "Jacky_Larson32@hotmail.com",
                            FirstName = "Jacky",
                            Gender = "Female",
                            HomePhone = "941-955-6230",
                            LastName = "Larson",
                            MiddleName = "Graciela"
                        },
                        new
                        {
                            Id = 35,
                            AddressName = "Cotton Gorgeous",
                            CompanyName = "Rice LLC",
                            DateOfBirth = new DateTime(1961, 9, 19, 19, 48, 14, 164, DateTimeKind.Local).AddTicks(7188),
                            Email = "Marilyne.Bogan@yahoo.com",
                            FirstName = "Marilyne",
                            Gender = "Male",
                            LastName = "Bogan",
                            MiddleName = "Sandrine"
                        },
                        new
                        {
                            Id = 36,
                            AddressName = "Practical sensor",
                            CompanyName = "Marquardt - Stoltenberg",
                            DateOfBirth = new DateTime(1991, 7, 16, 19, 26, 55, 283, DateTimeKind.Local).AddTicks(658),
                            Email = "Marge56@yahoo.com",
                            FirstName = "Marge",
                            Gender = "Male",
                            LastName = "Ondricka",
                            MiddleName = "Elouise",
                            WorkPhone = "841-455-9375"
                        },
                        new
                        {
                            Id = 37,
                            AddressName = "Director Intranet",
                            CellPhone = "679-979-9762",
                            CompanyName = "Krajcik, Stamm and Bernier",
                            DateOfBirth = new DateTime(1982, 5, 29, 8, 13, 24, 217, DateTimeKind.Local).AddTicks(2790),
                            Email = "Alberto78@gmail.com",
                            FirstName = "Alberto",
                            Gender = "Female",
                            HomePhone = "319-210-0501",
                            LastName = "Leffler",
                            MiddleName = "Chyna"
                        },
                        new
                        {
                            Id = 38,
                            AddressName = "deposit Centers",
                            CompanyName = "Padberg and Sons",
                            DateOfBirth = new DateTime(1970, 7, 27, 9, 19, 34, 396, DateTimeKind.Local).AddTicks(4994),
                            Email = "Hosea22@gmail.com",
                            FirstName = "Hosea",
                            Gender = "Female",
                            HomePhone = "931-234-6151",
                            LastName = "Orn",
                            MiddleName = "Jayce"
                        },
                        new
                        {
                            Id = 39,
                            AddressName = "Manor Unbranded Metal Pizza",
                            CompanyName = "Von Group",
                            DateOfBirth = new DateTime(1989, 6, 13, 2, 29, 14, 731, DateTimeKind.Local).AddTicks(2576),
                            Email = "Claude.Berge64@gmail.com",
                            FirstName = "Claude",
                            Gender = "Female",
                            LastName = "Berge",
                            MiddleName = "Dylan"
                        },
                        new
                        {
                            Id = 40,
                            AddressName = "grey Yuan Renminbi",
                            CellPhone = "680-766-9237",
                            CompanyName = "Herzog - Rau",
                            DateOfBirth = new DateTime(2001, 7, 31, 9, 51, 25, 970, DateTimeKind.Local).AddTicks(6646),
                            Email = "Marcelino21@hotmail.com",
                            FirstName = "Marcelino",
                            Gender = "Male",
                            HomePhone = "348-635-6769",
                            LastName = "Johns",
                            MiddleName = "Nia"
                        },
                        new
                        {
                            Id = 41,
                            AddressName = "bypassing convergence",
                            CellPhone = "674-294-3222",
                            CompanyName = "Leffler Group",
                            DateOfBirth = new DateTime(1991, 1, 11, 8, 17, 35, 164, DateTimeKind.Local).AddTicks(3599),
                            Email = "Axel87@gmail.com",
                            FirstName = "Axel",
                            Gender = "Male",
                            LastName = "O'Keefe",
                            MiddleName = "Obie"
                        },
                        new
                        {
                            Id = 42,
                            AddressName = "multi-byte Handcrafted Granite Computer",
                            CellPhone = "306-916-1366",
                            CompanyName = "Boyle - Kessler",
                            DateOfBirth = new DateTime(1956, 9, 13, 8, 33, 3, 816, DateTimeKind.Local).AddTicks(8295),
                            Email = "Cheyenne.Skiles@yahoo.com",
                            FirstName = "Cheyenne",
                            Gender = "Female",
                            LastName = "Skiles",
                            MiddleName = "Friedrich",
                            WorkPhone = "861-641-3098"
                        },
                        new
                        {
                            Id = 43,
                            AddressName = "Money Market Account Security",
                            CompanyName = "Kling - Braun",
                            DateOfBirth = new DateTime(1996, 8, 20, 10, 44, 5, 187, DateTimeKind.Local).AddTicks(3198),
                            Email = "Santos97@hotmail.com",
                            FirstName = "Santos",
                            Gender = "Female",
                            LastName = "Shanahan",
                            MiddleName = "Camylle"
                        },
                        new
                        {
                            Id = 44,
                            AddressName = "1080p Central",
                            CellPhone = "427-423-7509",
                            CompanyName = "O'Keefe - Rosenbaum",
                            DateOfBirth = new DateTime(1991, 3, 14, 6, 6, 12, 934, DateTimeKind.Local).AddTicks(2813),
                            Email = "Brook21@hotmail.com",
                            FirstName = "Brook",
                            Gender = "Female",
                            LastName = "Jacobs",
                            MiddleName = "Cassandre",
                            WorkPhone = "394-538-1039"
                        },
                        new
                        {
                            Id = 45,
                            AddressName = "Auto Loan Account Kroon",
                            CellPhone = "441-795-1740",
                            CompanyName = "Nader - Kohler",
                            DateOfBirth = new DateTime(1975, 3, 7, 21, 6, 40, 410, DateTimeKind.Local).AddTicks(2512),
                            Email = "Jailyn_Johnston7@yahoo.com",
                            FirstName = "Jailyn",
                            Gender = "Female",
                            HomePhone = "218-575-3315",
                            LastName = "Johnston",
                            MiddleName = "Zita",
                            WorkPhone = "893-831-4066"
                        },
                        new
                        {
                            Id = 46,
                            AddressName = "Forward Hollow",
                            CellPhone = "462-638-5414",
                            CompanyName = "Roberts, Schroeder and Boyer",
                            DateOfBirth = new DateTime(1983, 12, 4, 1, 0, 10, 288, DateTimeKind.Local).AddTicks(8964),
                            Email = "Otis_McLaughlin@gmail.com",
                            FirstName = "Otis",
                            Gender = "Male",
                            HomePhone = "925-511-9247",
                            LastName = "McLaughlin",
                            MiddleName = "Alessandra"
                        },
                        new
                        {
                            Id = 47,
                            AddressName = "Granite withdrawal",
                            CellPhone = "508-788-1762",
                            CompanyName = "Harris - Grant",
                            DateOfBirth = new DateTime(1954, 1, 18, 16, 36, 35, 596, DateTimeKind.Local).AddTicks(6093),
                            Email = "Jazmyn.Kutch@yahoo.com",
                            FirstName = "Jazmyn",
                            Gender = "Male",
                            HomePhone = "231-572-5768",
                            LastName = "Kutch",
                            MiddleName = "Ursula"
                        },
                        new
                        {
                            Id = 48,
                            AddressName = "Practical HDD",
                            CellPhone = "292-352-1643",
                            CompanyName = "Zemlak - Zemlak",
                            DateOfBirth = new DateTime(1969, 9, 1, 23, 5, 50, 857, DateTimeKind.Local).AddTicks(268),
                            Email = "Winfield.Hartmann@hotmail.com",
                            FirstName = "Winfield",
                            Gender = "Female",
                            HomePhone = "263-861-2284",
                            LastName = "Hartmann",
                            MiddleName = "Pasquale"
                        },
                        new
                        {
                            Id = 49,
                            AddressName = "Frozen Home Loan Account",
                            CompanyName = "Reichel LLC",
                            DateOfBirth = new DateTime(1964, 10, 7, 6, 26, 59, 451, DateTimeKind.Local).AddTicks(5972),
                            Email = "Owen12@yahoo.com",
                            FirstName = "Owen",
                            Gender = "Female",
                            HomePhone = "388-926-0644",
                            LastName = "Kozey",
                            MiddleName = "Tabitha"
                        },
                        new
                        {
                            Id = 50,
                            AddressName = "Re-engineered SAS",
                            CellPhone = "295-344-3220",
                            CompanyName = "Schmeler, Jast and Crona",
                            DateOfBirth = new DateTime(1973, 5, 25, 7, 56, 43, 240, DateTimeKind.Local).AddTicks(6158),
                            Email = "Albin1@yahoo.com",
                            FirstName = "Albin",
                            Gender = "Male",
                            HomePhone = "794-884-4374",
                            LastName = "Purdy",
                            MiddleName = "Uriel",
                            WorkPhone = "668-878-1340"
                        });
                });

            modelBuilder.Entity("AddressBook.Api.Data.Entities.Address", b =>
                {
                    b.HasOne("AddressBook.Api.Data.Entities.BookEntry", null)
                        .WithMany("Addresses")
                        .HasForeignKey("BookEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AddressBook.Api.Data.Entities.BookEntry", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
